#!/bin/zsh

# packages
sudo apt-get install -y \
  bat \
  fzf \
  neovim \
  silversearcher-ag

# starship
sudo sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --force
ln -s ./starship ~/.config/starship.toml

# vim
sudo sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
mkdir ~/.config/nvim
ln -s ./nvim ~/.config/nvim/init.vim
ln -s ~/.vimrc                  ~/.config/nvim/init.vim

# tmux
ln -s ./tmux ~/.tmux.conf

# shell
if [[ -z "$(grep ./shell ~/.zshrc)" ]]; then
  echo "source ./shell" >> ~/.zshrc
fi

exec $SHELL
